### ISSUE TITLE
Data attributes are not allowed in the HTML of items

### ISSUE THREAD

**Issue by tyxla** [2createStudio/carbon-pagination#27]
Data attributes can't be used within the HTML of the pagination items. This is due to wp_kses() stripping out all non-whitelisted attributes. Data attributes should be allowed. 

Props to @alpanayotov for reporting.

**Comment by tyxla** [comment]
WP KSES is currently used for making sure evil scripts are escaped when rendering the pagination. This is purposely done with security purposes and should remain so.

Anyone who wants to use `data-` attributes within the pagination HTML has two possible solutions:

1) **Recommended**: Adding the data attributes to the list of allowed attributes with the `wp_kses_allowed_html` filter, like this:

``` php
add_filter( 'wp_kses_allowed_html', 'carbon_pagination_kses_allowed_html', 10, 2 );
function carbon_pagination_kses_allowed_html( $allowed, $context ) {
    $allowed[ 'a' ][ 'data-example' ] = true;
    return $allowed;
}
```

This will add the `data-example` data attribute to the whitelist as a valid attribute.

2) **Not recommended:** Using carbon pagination with `echo: false`, and manually render without escaping the output. For example:

``` php
echo carbon_pagination( 'posts', array(), false );
```

where the `posts` is the pagination type, the `array()` contains the pagination arguments and the `false` is the `echo` setting. This method is not recommended because it skips the security measures.

**Comment by alpanayotovv** [comment]
Nice :) Please add this a "known issue" in the Readme, so others might find it easy :)
