### ISSUE TITLE
Automatic wrapper classes for major settings

### ISSUE THREAD

**Issue by pkostadinov-2create** [2createStudio/carbon-pagination#28]
It would be extremely useful for styling, to have different wrapper classes depending on **key** settings.

Here is an example:
- `div.paging` - always present
- `div.paging-prev-next` - added when `enable_prev` && `enable_next` set to `true`
- `div.paging-first-last` - added when `enable_first` && `enable_last`  set to `true`
- `div.paging-numbers` - added when `enable_numbers` set to `true`

**Comment by tyxla** [comment]
Hey @pkostadinov-2create,

IMHO, some settings can be **key** for one person, and not **key** for another person - it is a matter of perspective. So for example if `paging-prev-next` and `paging-first-last` make sense to you, they wouldn't make much sense to somebody else. 

Now to the point. The plugin allows the CSS classes to be modified by altering the wrapper HTML settings. You have full control there. Considering the fact that you can easily change the wrapper HTML (the `<div class="paging">` and the closing `</div>`) and the settings, you can easily create your logic that would build the CSS classes string based on your **key** settings. 

Considering the ambiguity of whether a setting is **key** or not and the ease of implementing your own custom CSS class logic, I don't see a good reason to implement this feature at this time.

Thanks for the idea anyway!
