### ISSUE TITLE
Wrong default values for Prev/Next posts buttons' HTML in readme

### ISSUE THREAD

**Issue by kaloyan-dev** [2createStudio/carbon-pagination#29]
It seems there is a slight mismatch between the default values in the readme and in the actual code.

Default values in readme:

```
'prev_html' => '<a href="{URL}" class="paging-prev"></a>',
'next_html' => '<a href="{URL}" class="paging-next"></a>',
```

Default values in [code](https://github.com/2createStudio/carbon-pagination/blob/master/includes/paginations/Carbon_Pagination_Posts.php#L27-L31):

```
'prev_html' => '<a href="{URL}" class="paging-prev">' . esc_html__( '« Previous Entries', 'crb' ) . '</a>',
'next_html' => '<a href="{URL}" class="paging-next">' . esc_html__( 'Next Entries »', 'crb' ) . '</a>',
```

**Comment by tyxla** [comment]
Thanks for reporting!
