### ISSUE TITLE
Carbon_Pagination_Custom preservation of custom `$_GET` query vars

### ISSUE THREAD

**Issue by alpanayotovv** [2createStudio/carbon-pagination#30]
Currently the `get_page_url` method within the `Carbon_Pagination_Custom` class does not take into consideration any previously set query vars.

Possible solution:

Adding a filter that allows the passing of an array containing the desired query custom vars and merging this array with the  `$this->get_query_var(), $pages[ $page_number ]` pair.

**Comment by tyxla** [comment]
Hey @alpanayotov,

This is being done on purpose. Main reason: unnecessary GET vars should not be kept when building the links - only a certain set of them should be accepted.

Basically, the `GET` vars are not necessarily query vars. If you take a look at `Carbon_Pagination_Utilities::get_current_url()` which retrieves the current URL you will notice 2 cases:
1. When default (empty) permalink structure is used, all query vars will be preserved as GET parameters.
2. When a custom permalink structure is used, GET parameters will be preserved only if they're also registered as query vars (either through the `query_vars` filter, or registed as rewrite tags by using `add_rewrite_tag()`).

So, you're probably asking what you should do? It's quite simple. Register all GET vars that you want to keep as query vars - either through the `query_vars` filter, or registed as rewrite tags by using `add_rewrite_tag()`.

Don't hesitate to reopen the issue if you have any further questions or trouble.
