### ISSUE TITLE
Refactor Carbon_Pagination_Builder::build_page_links()

### ISSUE THREAD

**Issue by emohamed** [2createStudio/carbon-pagination#7]
`Carbon_Pagination_Builder::build_page_links` method seems too long, complex and repetitive. 

Especially the blocks that handle large page number links(before and after).

**Comment by tyxla** [comment]
The library has been refactored, there are no longer any that complex repetitive methods. There is no builder anymore - the new version works with Items (which are objects), contained and managed in Collections, which are then displayed by Renderers.
